version: '3.8'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    volumes:
      - ./seeds:/usr/src/app/seeds
      - ./generated:/usr/src/app/generated
    networks:
      - postgres
  db:
      container_name: postgres_rpjooj
      image: postgres
      restart: unless-stopped
      volumes:
        - ./data:/var/lib/postgresql/data
      env_file:
        - .env
      ports:
        - 5432:5432
      networks:
        - postgres

networks:
  postgres:
    driver: bridge
volumes:
  data:
